SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `CORONA_ACCESS` (
  `USER_ID` varchar(13) NOT NULL,
  `ACCESS_DATE` datetime NOT NULL,
  `ROUTE` varchar(10) NOT NULL COMMENT '手段',
  `MESSAGE` varchar(255) NOT NULL,
  PRIMARY KEY (`USER_ID`,`ACCESS_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `CORONA_M_CODE` (
  `KUBUN` varchar(5) NOT NULL COMMENT '区分(5)',
  `CODE` int(10) NOT NULL COMMENT 'コード(10)',
  `NAME` varchar(300) NOT NULL COMMENT '名称(30)',
  PRIMARY KEY (`KUBUN`,`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='区分マスタ';

CREATE TABLE IF NOT EXISTS `CORONA_M_COMPANY` (
  `COMPANY_CODE` int(2) NOT NULL COMMENT '会社コード(2)',
  `COMPANY_NAME` varchar(500) NOT NULL COMMENT '会社名(30)',
  `COMPANY_POST` varchar(500) NOT NULL COMMENT '会社郵便番号(10)',
  `COMPANY_KEN` varchar(500) NOT NULL COMMENT '会社都道府県(10)',
  `COMPANY_SHI` varchar(500) NOT NULL COMMENT '会社市区町村(20)',
  `COMPANY_ADDRESS1` varchar(500) NOT NULL COMMENT '会社住所１(50)',
  `COMPANY_ADDRESS2` varchar(500) NOT NULL COMMENT '会社住所２(50)',
  `COMPANY_TEL` varchar(500) NOT NULL COMMENT '会社電話番号(15)',
  `COMPANY_WEB` varchar(500) NOT NULL COMMENT '会社ホームページ(100)',
  `COMPANY_MAIL` varchar(200) NOT NULL COMMENT '会社メールアドレス(50)',
  `COMPANY_HOST` varchar(300) NOT NULL COMMENT '会社メール送信ホスト(40)',
  `COMPANY_PORT` int(10) NOT NULL COMMENT '会社メール送信ポート(10)',
  `COMPANY_ID` varchar(300) NOT NULL COMMENT '会社メール送信ユーザー名(100)',
  `COMPANY_PASS` varchar(300) NOT NULL COMMENT '会社メール送信パスワード(20)',
  `COMPANY_ENDDATE` date NOT NULL COMMENT '会社終了日',
  PRIMARY KEY (`COMPANY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会社情報';

CREATE TABLE IF NOT EXISTS `CORONA_M_MEMBER` (
  `COMPANY_CODE` int(2) NOT NULL COMMENT '会社コード(2)',
  `MEMBER_CODE` varchar(10) NOT NULL COMMENT 'ユーザーコード(10)',
  `MEMBER_PASS` varchar(500) NOT NULL COMMENT 'パスワード(10)',
  `MEMBER_NAME` varchar(500) NOT NULL COMMENT 'ユーザー名(20)',
  `MEMBER_MAIL` varchar(200) NOT NULL COMMENT 'ユーザーメールアドレス(50)',
  `MEMBER_AUTHORITY` int(1) NOT NULL COMMENT 'ユーザー権限（1:システム管理者2:システム担当者3:ユーザー管理者4:ユーザー担当者5:その他ユーザー）',
  `MEMBER_ENABLE` int(1) NOT NULL COMMENT 'ユーザー有効フラグ（1:有効　0:無効）',
  `MEMBER_LOGIN` varchar(300) NOT NULL COMMENT 'ログイン識別番号',
  PRIMARY KEY (`MEMBER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ユーザーマスタ';

CREATE TABLE IF NOT EXISTS `CORONA_T_INFORMATION` (
  `INFO_CODE` int(10) NOT NULL AUTO_INCREMENT COMMENT 'お知らせコード（10）',
  `INFO_TITLE` varchar(500) NOT NULL COMMENT 'お知らせタイトル（20）',
  `INFO_DETAIL` text NOT NULL COMMENT 'お知らせ内容（500）',
  `INFO_TYPE` int(1) NOT NULL COMMENT 'お知らせ種類（1）（0：通常　1：重要　2：緊急）',
  `INFO_STARTDATE` date NOT NULL COMMENT 'お知らせ開始日',
  `INFO_ENDDATE` date NOT NULL COMMENT 'お知らせ終了日',
  `INFO_AUTHORITY` char(6) NOT NULL DEFAULT '000000' COMMENT 'お知らせ表示権限（6）　未ログイン者含む',
  PRIMARY KEY (`INFO_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='お知らせ情報' AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `CORONA_USER` (
  `USER_ID` varchar(13) NOT NULL COMMENT 'ユーザーID',
  `LINE_ID` varchar(500) NOT NULL COMMENT 'LINEID',
  `COMPANY_CODE` int(2) NOT NULL,
  `USER_NAME` varchar(500) NOT NULL COMMENT '氏名',
  `USER_CONTACT_NO` varchar(500) NOT NULL COMMENT '連絡先',
  `USER_ADDRESS` varchar(500) NOT NULL COMMENT '住所',
  `USER_AGE` int(3) NOT NULL COMMENT '年齢',
  `USER_SEX` varchar(1) NOT NULL COMMENT '性別',
  `LAST_ACCESS` datetime NOT NULL,
  `USER_STATUS` varchar(10) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `CORONA_W_LOG` (
  `LOG_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ログID',
  `LOG_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'ログ日付',
  `LOG_TYPE` varchar(10) NOT NULL COMMENT 'ログタイプ(10)',
  `MEMBER_CODE` varchar(10) NOT NULL COMMENT 'ユーザーコード(10)',
  `LOG_FILENAME` varchar(100) NOT NULL COMMENT 'ログファイル名',
  `LOG_MESSAGE` text NOT NULL COMMENT 'ログメッセージ',
  PRIMARY KEY (`LOG_NO`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='ログテーブル' AUTO_INCREMENT=473 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
